export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_ARTIST_SUCCESS = "FETCH_ARTIST_SUCCESS";
export const FETCH_ARTIST_ERROR = "FETCH_ARTIST_ERROR";

export const FETCH_ALBUM_SUCCESS = "FETCH_ALBUM_SUCCESS";
export const FETCH_ALBUM_ERROR = "FETCH_ALBUM_ERROR";

export const FETCH_TRACK_SUCCESS = "FETCH_TRACK_SUCCESS";
export const FETCH_TRACK_ERROR = "FETCH_TRACK_ERROR";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_TRACK_HISTORY_SUCCESS = 'FETCH_TRACK_HISTORY_SUCCESS';
export const FETCH_TRACK_HISTORY_ERROR = 'FETCH_TRACK_HISTORY_ERROR';
export const POST_TRACK_HISTORY_ERROR = 'POST_TRACK_HISTORY_ERROR';

export const POST_ARTIST = 'POST_ARTIST';
export const POST_ARTIST_SUCCESS = 'POST_ARTIST_SUCCESS';
export const POST_ARTIST_ERROR = 'POST_ARTIST_ERROR';

export const POST_ALBUM = 'POST_ALBUM';
export const POST_ALBUM_SUCCESS = 'POST_ALBUM_SUCCESS';
export const POST_ALBUM_ERROR = 'POST_ALBUM_ERROR';

export const POST_TRACK = 'POST_TRACK';
export const POST_TRACK_SUCCESS = 'POST_TRACK_SUCCESS';
export const POST_TRACK_ERROR = 'POST_TRACK_ERROR';

export const STOP_LOADING = 'STOP_LOADING';

export const FETCH_USER_ARTIST_REQUEST = "FETCH_USER_ARTIST_REQUEST";
export const FETCH_USER_ARTIST_SUCCESS = "FETCH_USER_ARTIST_SUCCESS";
export const FETCH_USER_ARTIST_ERROR = "FETCH_USER_ARTIST_ERROR";

export const FETCH_USER_ALBUM = "FETCH_USER_ALBUM";
export const FETCH_USER_ALBUM_SUCCESS = "FETCH_USER_ALBUM_SUCCESS";
export const FETCH_USER_ALBUM_ERROR = "FETCH_USER_ALBUM_ERROR";

export const FETCH_USER_TRACK = "FETCH_USER_TRACK";
export const FETCH_USER_TRACK_SUCCESS = "FETCH_USER_TRACK_SUCCESS";
export const FETCH_USER_TRACK_ERROR = "FETCH_USER_TRACK_ERROR";


export const FETCH_ADMIN_ARTIST = "FETCH_ADMIN_ARTIST";
export const PUT_ADMIN_ARTIST_SUCCESS = "PUT_ADMIN_ARTIST_SUCCESS";
export const DELETE_ADMIN_ARTIST_SUCCESS = "DELETE_ADMIN_ARTIST_SUCCESS";
export const FETCH_ADMIN_ARTIST_ERROR = "FETCH_ADMIN_ARTIST_ERROR";

export const FETCH_ADMIN_ALBUM = "FETCH_ADMIN_ALBUM";
export const PUT_ADMIN_ALBUM_SUCCESS = "PUT_ADMIN_ALBUM_SUCCESS";
export const DELETE_ADMIN_ALBUM_SUCCESS = "DELETE_ADMIN_ALBUM_SUCCESS";
export const FETCH_ADMIN_ALBUM_ERROR = "FETCH_ADMIN_ALBUM_ERROR";

export const FETCH_ADMIN_TRACK = "FETCH_ADMIN_TRACK";
export const PUT_ADMIN_TRACK_SUCCESS = "PUT_ADMIN_TRACK_SUCCESS";
export const DELETE_ADMIN_TRACK_SUCCESS = "DELETE_ADMIN_TRACK_SUCCESS";
export const FETCH_ADMIN_TRACK_ERROR = "FETCH_ADMIN_TRACK_ERROR";